### PR TITLE
example_full: with blacklist

### PR DESCRIPTION
**Pull request by honwen**
- fix some upstreams
- add blacklist example

### CODE REVIEW

**Comment by LEXUGE** [comment]
Actually I am considering to maintain a separated repository with dcompass configs.

**Comment by honwen** [comment]
reasonable

**Comment by LEXUGE** [comment]
Would you like to migrate this PR to the `configs` repo?

**Comment by honwen** [comment]
ok, at weekend

**Comment by honwen** [comment]
move to https://github.com/compassd/configs/pull/2

**Pull request closed without merging**
